### ISSUE TITLE
Latest Commit Won't Build

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Andrews54757/tweakfork#12]
This is the entire text in CMD:
https://gist.github.com/DragonEggBedrockBreaking/4ffc7e95f9764819b7b0a30c908c7b7e

**Comment by Andrews54757** [comment]
it works for me XD. It seems like you need to delete the gradle caches. Since #11 , fabric-loom has been swapped for chocohead's fabric-loom.
