### ISSUE TITLE
[Feature Requests]

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Andrews54757/tweakfork#15]
- [ ] Hangable entity bypass for signs

**Comment by Andrews54757** [comment]
maybe, no, and idk what that is.

**Comment by DragonEggBedrockBreaking** [comment]
> maybe, no, and idk what that is.

Hangable entity bypass allows you to open chests through item frames and paintings. Masa said more work needed to be done to make it work with signs.

**Comment by ElvarTheTurtle** [comment]
I think there is already a mod that does that

**Comment by DragonEggBedrockBreaking** [comment]
> I think there is already a mod that does that

There are many mods that add different client features, but the nice thing is that tweakeroo/tweakfork puts them together in one easy to access, toggleable, non-cluttered mod.
