### ISSUE TITLE
Only empty shulkerbox stacking from the All stackable mod doesn't work with tweakfork 

### ISSUE THREAD

**Issue by SpacEagle17** [Andrews54757/tweakfork#24]
The following config file has to be placed into the world folder like this 
![image](https://user-images.githubusercontent.com/46494907/132002942-c0c13533-4d06-4488-98e8-b22f72de8193.png)
the txt also has to be renamed to .json (github doesn't allow direct json upload)
[allstackable-config.txt](https://github.com/Andrews54757/tweakfork/files/7105743/allstackable-config.txt)
That config file should make all shulker boxes stackable but only when they are empty. But all shulker boxes stack, regardeless if they are emty or not. It works perfectly fine with tweakeroo (only the empty ones stack) but not with tweakfork. I deleted the tweakeroo config file as well to test if it was because of my settings, but that isn't the case.
Minecraft version: 1.16.5
Fabric loader: 0.11.6
JDK 16 (necessary for that All Stackable version)
Mods while testing:
AllStackable-1.4.1-1.16.5
fabric-api-0.40.0+1.16
malilib-fabric-1.16.4-0.10.0-dev.21+arne.5
tweakfork-fabric-1.16.4-1.2.1 / tweakeroo-fabric-1.16.4-0.10.0-dev.20210303.123654
I hope this helps

**Comment by Yukino0812** [comment]
It seems to be the conflict between `tweakroo` and `AllStackable`. 
Both of them inject code at the head of `ItemStack#getMaxCount()`.

tweakroo mixin
https://github.com/maruohon/tweakeroo/blob/04f19d11b94f8ab3ea8b550ed612076a8dcafe64/src/main/java/fi/dy/masa/tweakeroo/mixin/MixinItemStack.java#L18-L22

AllStackable mixin
https://github.com/KrisCris/AllStackable/blob/1261d7c92ab0494fada65daf064bee12d06ff6d7/src/main/java/me/connlost/allstackable/mixin/MixinItemStack.java#L22-L33
