### ISSUE TITLE
Problem with Fast Left Click

### ISSUE THREAD

**Issue by Gavirium** [Andrews54757/tweakfork#29]
When I use Tweakfork instead of Tweakeroo, the "tweakFastLeftClick" feature doesn't seem to work.
I use Version 1.2.3 of the mod.
Is there any reason why it would happen?

**Comment by DragonEggBedrockBreaking** [comment]
`tweakFastLeftClick` only works in creative mode. For survival mode, enable `tweakFastLeftClickAllowTools`. This was added in the latest tweakeroo and tweakfork additions, so if you switched from an outdated tweakeroo to the latest tweakfork this is likely the case.

**Comment by Gavirium** [comment]
Thanks alot, but where do I find this feature. I've searched under every tab, in the tweakfork configs.

**Comment by DragonEggBedrockBreaking** [comment]
Make sure you are using the latest tweakfork version
