### ISSUE TITLE
[SUGGESTION] add InventoryScan in-inventory item highlight

### ISSUE THREAD

**Issue by Pietr06** [Andrews54757/tweakfork#48]
i have found many times frustrating that when searching for an item that is boxed inside a shulker in a container, it only tells me in wich chest i should search, but then i have to go trough all the shulkers and check for my item, it would be very useful if it cuold highlight the certain shulker where the item is, and maybe also the item if its not in a shulker, also litematica already does a similar thing, it highlight the block of the schem you are looking at, so you could take that code and modify it idk

**Comment by Andrews54757** [comment]
maybe if I can stop lazy. I accept pull requests.

**Comment by fooeyround** [comment]
https://github.com/Andrews54757/tweakfork/pull/53 
does this

**Comment by fooeyround** [comment]
implementation for search can be better..

**Comment by fooeyround** [comment]
but it should be fine unless the cache could be used to not make the same operations all the time....
