### ISSUE TITLE
[FR] White/black list selective block types

### ISSUE THREAD

**Issue by vlad2305m** [Andrews54757/tweakfork#49]
I started working on it in https://github.com/vlad2305m/tweakfork-1.19.3. 
It would be nice to be able to blacklist certain block types in an area, as traking will be hard for some (ex. water/lava/leaves)

Also, look in your forks tab before doing all the work yourself :) Especially after leaving us without updates for such a long time

**Comment by Andrews54757** [comment]
feel free to make a pull request when you are done. I don't mind if people fork, this project is for my own personal use anyways so a lot of the features/updates will be on a need basis.
