### ISSUE TITLE
Add the mods in mcmod.cn

### ISSUE THREAD

**Issue by phishinqi** [Andrews54757/tweakfork#50]
Hi, I like your mods, can I move it to mcmod.cn to let more people know it?
mcmod.cn is the Chinese Minecraft Mods Wiki, which is used by many Chinese Minecraft players.
I will keep the Github link and provide the Github download link for the mods.

**Comment by Andrews54757** [comment]
sure but no guarantee that I will update regularly.

**Comment by phishinqi** [comment]
> 当然，但不能保证我会定期更新。

Thanks, I have created the relevant page for the mod. (Even though it looks so rudimentary now, I will update it later.)
Link:https://www.mcmod.cn/class/9610.html
