### ISSUE TITLE
update 1.20.1

### ISSUE THREAD

**Issue by Bobisawesome07** [Andrews54757/tweakfork#55]
Please update the mod to 1.20.1 it is very useful.

**Comment by miguelguerra1907187** [comment]
that will help a lot plz update to 1.20 or 1.20.1

**Comment by m0oncatcher** [comment]
Bump

**Comment by P3nguinMinecraft** [comment]
I would also like the mod to be updated to 1.20

**Comment by Andrews54757** [comment]
done
https://github.com/Andrews54757/tweakfork/releases
