### ISSUE TITLE
Piston info tweak does not remove piston counts when it is destroyed

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Andrews54757/tweakfork#6]
Pistorder now has the feature that the overlay is removed when the piston is broken, but this feature is not yet in tweakfork. After getting used to this feature in pistorder, it is annoying that it is not here, and it feels pointless to have multiple mods when you can get the job done with only one.

**Comment by Andrews54757** [comment]
All the code for that has already been added since the first commit adding the piston order feature, it just hasn't been hooked into the game's events. It will be done soon™

**Comment by DragonEggBedrockBreaking** [comment]
OK. Should I close this, or will you do so when you've hooked it into the game's events?

**Comment by Andrews54757** [comment]
Implemented with https://github.com/Andrews54757/tweakfork/commit/ce6e445d655d11297faeed91337aa4f261c49fe1
